### ISSUE TITLE
Support for Battle Pass "Prestige" levels?

### ISSUE THREAD

**Issue by Traymoir** [sophice/ow2-battle-pass-calculator#1]
After level 80 there are 120 additional levels (so 200 in total) that award player titles. I believe it amounts to an additional 1.2mil BP exp to max out completely.

Maybe the field for BP level could be manually entered in case the user isn't planning on making it to 80, or is going to grind prestige levels.

Thanks for the awesome tool!

**Comment by sophice** [comment]
Glad you like it, and thanks so much for the feedback!

I forgot about that system. Do you know how it's structured? So it's 120 more tiers, 10,000 XP each? And how many titles are there/how are they spread out?

I will add an additional note to the projected/expected sections saying how many prestige tiers you'll reach (if any), that might be all that's needed for it.

**Comment by sophice** [comment]
I think this is the structure after a little digging;

* 85, 50,000 XP, "Nomad"
* 95, 100,000 XP, "Neogun"
* 105, 100,000 XP, "Streetrunner"
* 120, 150,000 XP, "Bytefixer"
* 135, 150,000 XP, "Netbreaker"
* 155, 200,000 XP, "Data Broker"
* 175, 200,000 XP, "Technoknight"
* 200, 250,000 XP, "Cyberdemon"

**Comment by Traymoir** [comment]
After 80 there are 8 tiers that each award a title. Here's what level each tier unlocks at:

- Tier 1: 85
- Tier 2: 95
- Tier 3: 105
- Tier 4: 120
- Tier 5: 135
- Tier 6: 155
- Tier 7: 175
- Tier 8: 200

Within those tiers just multiply the amount of levels WITHIN that tier by 10,000. So obtaining Tier 1 requires 50,000 exp (80-85), Tier 2 requires 100,000 exp (85-95) and so on for the increasing levels between these tiers.

Update after reading your comment: Yep, you seem spot on.

**Comment by sophice** [comment]
Added! I might improve the messaging but at least for now it's there. If you will make it past tier 80 it will tell you, and it will also tell you how many titles you will earn, for both projected and expected scenarios.
